export const AGREGAR_POST = 'AGREGAR_POST'
export const AGREGAR_POST_EXITO = 'AGREGAR_POST_EXITO'
export const AGREGAR_POST_ERROR = 'AGREGAR_POST_ERROR'

export const COMENZAR_DESCARGA_POSTS = 'COMENZAR_DESCARGA_POSTS'
export const COMENZAR_DESCARGA_POSTS_EXITO = 'COMENZAR_DESCARGA_POSTS_EXITO'
export const COMENZAR_DESCARGA_POSTS_ERROR = 'COMENZAR_DESCARGA_POSTS_ERROR'

export const AGREGAR_COMENTARIO = 'AGREGAR_COMENTARIO'
export const AGREGAR_COMENTARIO_EXITO = 'AGREGAR_COMENTARIO_EXITO'
export const AGREGAR_COMENTARIO_ERROR = 'AGREGAR_COMENTARIO_ERROR'


